FROM golang:1.20-alpine AS BUILDER

ENV USER=application
ENV UID=10001

RUN adduser --disabled-password  \
    --home "/nonexistent"  \
    --shell "/sbin/nologin" \
    --no-create-home  \
    --uid "${UID}"  \
    --gecos "" \
    "${USER}"

FROM scratch

COPY --from=BUILDER /etc/passwd /etc/passwd
COPY --from=BUILDER /etc/group /etc/group
COPY service /service
USER application:application
ENTRYPOINT ["/service"]