name: Main

on:
  push:
    paths-ignore:
      - '.github/workflows/pr.yml'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - name: go tests
        run: go test -race -cover ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m

  build:
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - name: Docker login
        run: docker login ghcr.io -u heartwilltell -p ${{ github.token }}

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-X main.Branch=${{ github.ref_name }} -X main.Commit=${{ github.sha }}" -o service ./cmd
          docker build -f Dockerfile-static \
          -t ghcr.io/heartwilltell/portservice/service:${{ github.sha }} \
          -t ghcr.io/heartwilltell/portservice/service:latest \
          --progress=plain .

      - name: Docker push
        run: |
          docker push ghcr.io/heartwilltell/portservice/service:${{ github.sha }}
          docker push ghcr.io/heartwilltell/portservice/service:latest