name: Pull Request

on:
  pull_request:
    paths-ignore:
      - '.github/workflows/deploy.yml'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - name: go test
        run: go test -race -cover ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - name: golangci-lint run
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m